on: [push]

jobs:
  render_jsonnet_to_stdout:
    runs-on: ubuntu-latest
    name: Execute Jsonnet, print to STDOUT
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Jsonnet
        uses: ./
        id: jsonnet
        with:
          file: 'test/example.jsonnet'
  render_jsonnet_to_single_file:
    runs-on: ubuntu-latest
    name: Execute Jsonnet and direct STDOUT to file
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Jsonnet
        uses: ./
        id: jsonnet
        with:
          file: 'test/example.jsonnet'
          output_file: test/output.json
      - name: Validation
        run: diff test/output.json test/expected-example.json
  render_jsonnet_to_multiple_files:
    runs-on: ubuntu-latest
    name: Execute Jsonnet, render multiple output files
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Jsonnet
        uses: ./
        id: jsonnet
        with:
          file: 'test/example.jsonnet'
          output_dir: test/multi-file-output/
      - name: Validation
        run: diff test/multi-file-output/person1 test/person1
