on: [push]

jobs:
  render_jsonnet_to_stdout:
    runs-on: ubuntu-latest
    name: Execute Jsonnet
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Jsonnet
        uses: ./ # Uses an action in the root directory
        id: jsonnet
        with:
          file: 'test/example.jsonnet'
